site_name: Java Chassis 3 开发指南
use_directory_urls: false

nav:

- 概述 : index.md
- Java Chassis设计参考: start/design.md
- Java Chassis 3版本介绍 : introduce3.x.x.md
- 快速入门:
  - 安装本地开发环境: start/development-environment.md
  - 开发第一个微服务应用: start/first-sample.md
  - BMI应用-使用服务治理: featured-topics/application-bmi.md
  - PORTER应用-典型开发场景: featured-topics/application-porter.md
- 微服务定义: build-provider/definition/service-definition.md
- Spring Boot集成Java Chassis:
    - Spring Boot集成Java Chassis介绍: spring-boot/introduction.md
    - 与Spring Web MVC开发习惯的差异: spring-boot/diff-spring-mvc.md
- 开发服务提供者:
    - 基础概念: build-provider/basics.md
    - HTTP参数映射参考: build-provider/http-mapping.md
    - 用JAX-RS开发微服务: build-provider/jaxrs.md
    - 用SpringMVC开发微服务: build-provider/springmvc.md
    - 用透明RPC开发微服务: build-provider/transparent-rpc.md
    - 使用Swagger注解: build-provider/swagger-annotation.md
    - 只发布interface的方法为服务接口: build-provider/use-interface.md
    - 异步处理: build-provider/reactive.md
    - 使用 Context 参数: build-provider/context-param.md
    - 多个返回值和错误码: build-provider/multi-code.md
    - 接口定义和数据类型: build-provider/interface-constraints.md
    - 服务监听地址和发布地址: build-provider/listen-address-and-publish-address.md
    - 线程池: build-provider/thread-pool.md
    - 服务启动事件: build-provider/event-listener.md
    - 参数效验: build-provider/parameter-validator.md
    - 程序启动逻辑: build-provider/bootup.md
    - IPV6配置和使用: build-provider/ipv6-configuration.md
- 开发服务消费者:
    - 基础概念: build-consumer/basics.md
    - Restful风格 - 使用 RestOperations: build-consumer/using-resttemplate.md
    - RPC风格: build-consumer/develop-consumer-using-rpc.md
    - 泛化调用: build-consumer/invoker.md
- 定制请求处理流程:
    - 处理链介绍: references-handlers/intruduction.md
- 通用功能开发:
    - 本地开发和测试: general-development/local-develop-test.md
    - 文件上传下载: general-development/upload-download.md
    - Reactive: general-development/reactive.md
    - DNS自定义配置: general-development/dnsconfig.md
    - 代理设置: general-development/proxy.md
    - 框架上报版本号: general-development/report-framework-version.md
    - 跨应用调用: general-development/cross-app-invocation.md
    - 定制序列化和反序列化方法: general-development/secret-field.md
    - 使用Context传递控制消息: general-development/context.md
    - 返回值序列化扩展: general-development/produceprocess.md
    - 跨域资源共享(CORS): general-development/CORS.md
    - 获取熔断与实例隔离告警事件信息: general-development/AlarmEvent.md
    - 优雅停机: general-development/shutdown.md
    - 异常处理: general-development/error-handling.md
    - 微服务实例间多环境隔离: general-development/multienvironment.md
    - 线程模型: general-development/thread-model.md
    - 配置日志: general-development/config-logs.md
- 多样化的通信协议功能:
    - 多协议介绍: transports/introduction.md
    - REST over HTTP(Vert.x): transports/rest-over-vertx.md
    - REST over HTTP2(Vert.x): transports/http2.md
    - REST over Servlet(Spring Boot Embedded): transports/rest-over-servlet-embedded.md
    - REST over Servlet(WAR): transports/rest-over-servlet.md
    - Highway: transports/highway-rpc.md
- 多样化的服务注册与发现功能:
    - 注册发现介绍: registry/introduction.md
    - 使用Service Center: registry/service-center.md
    - 使用Nacos: registry/nacos.md
    - 使用ZooKeeper: registry/zookeeper.md
    - 本地注册发现: registry/local-registry.md
    - 去中心化注册发现: registry/distributed.md
- 多样化的配置管理功能:
    - 服务配置介绍: config/general-config.md
    - 在程序中读取配置信息: config/read-config.md
    - 使用Kie: config/kie.md
    - 使用Nacos: config/nacos.md
    - 使用Zookeeper: config/zookeeper.md
    - 使用Apollo: config/apollo.md
    - 使用CSE1.0配置中心: config/cse1.md
- 服务治理功能参考:
    - 流量特征治理: references-handlers/rule-governance.md
    - 流量特征治理最佳实践: references-handlers/governance-best-practise.md
    - 负载均衡: references-handlers/loadbalance.md
    - 限流: references-handlers/ratelimit.md
    - 灰度发布: references-handlers/router.md
    - 故障注入: references-handlers/fault-injection.md
    - 快速失败和重试: references-handlers/fail-retry.md
- 网关功能参考:
    - 介绍: edge/open-service.md
    - 使用 Edge Service 做网关: edge/by-servicecomb-sdk.md
    - 使用 `zuul` 和 `spring cloud gateway` 做网关: edge/zuul.md
    - nginx 网关简单介绍: edge/nginx.md
- 安全特性参考:
    - 微服务间认证: security/publickey.md
    - 使用TLS通信: security/tls.md
- 可观测功能参考:
    - 应用性能监控: general-development/metrics.md
    - 微服务调用链: general-development/microservice-invocation-chain.md
    - Access Log配置: build-provider/access-log-configuration.md

- 专题文章:
    - 特性介绍: featured-topics/features.md
    - 技术解密: featured-topics/secrets.md
    - 升级指导: featured-topics/upgrading.md
    - 兼容问题和兼容性策略: featured-topics/compatibility.md
    - 性能问题分析和调优: featured-topics/performance.md
- 常用配置项参考:
    - REST Transport Client 配置项: config-reference/rest-transport-client.md
- 常见问题:
    - 'FAQ' : question-and-answer/faq.md
    - 'Q & A' : question-and-answer/question_answer.md
    - 微服务接口兼容常见问题: question-and-answer/interface-compatibility.md
theme: material
plugins:
    - search
