site_name: ServiceComb Java Chassis 开发指南
use_directory_urls: false

nav:

- 概述 : index.md
- Java Chassis设计参考: start/design.md
- 3.x.x 版本介绍 : introduce3.x.x.md
- 快速入门:
  - 术语表: start/terminology.md
  - 微服务系统架构: start/architecture.md
  - 安装本地开发环境: start/development-environment.md
  - 开发第一个微服务应用: start/first-sample.md
  - 完整例子-bmi应用: featured-topics/application-bmi.md
  - 完整例子-porter应用: featured-topics/application-porter.md
- 微服务定义: build-provider/definition/service-definition.md
- Spring Boot集成Java Chassis:
    - Spring Boot集成Java Chassis介绍: spring-boot/introduction.md
    - 与Spring Web MVC开发习惯的差异: spring-boot/diff-spring-mvc.md
- 开发服务提供者: build-provider/catalog.md
- 开发服务消费者: build-consumer/catalog.md
- 通用功能开发: general-development/catalog.md
- 多样化的通信协议功能:
    - 多协议介绍: transports/introduction.md
    - REST over HTTP(Vert.x): transports/rest-over-vertx.md
    - REST over HTTP2(Vert.x): transports/http2.md
    - REST over Servlet(Spring Boot Embedded): transports/rest-over-servlet-embedded.md
    - REST over Servlet(WAR): transports/rest-over-servlet.md
    - Highway: transports/highway-rpc.md
- 多样化的服务注册与发现功能:
    - 注册发现介绍: registry/introduction.md
    - 使用service-center: registry/service-center.md
    - 使用nacos: registry/nacos.md
    - 本地注册发现: registry/local-registry.md
    - 去中心化注册发现: registry/distributed.md
- 多样化的配置管理功能:
    - 服务配置介绍: config/general-config.md
    - 在程序中读取配置信息: config/read-config.md
    - 配置中心参考: config/config-service.md
- 服务治理功能参考:
      - 处理链介绍: references-handlers/intruduction.md
      - 负载均衡: references-handlers/loadbalance.md
      - 限流: references-handlers/ratelimit.md
      - 灰度发布: references-handlers/router.md
      - 故障注入: references-handlers/fault-injection.md
      - 流量特征治理: references-handlers/governance.md
      - 快速失败和重试: references-handlers/fail-retry.md
- 网关功能参考:
      - 介绍: edge/open-service.md
      - 使用 Edge Service 做网关: edge/by-servicecomb-sdk.md
      - 使用 `zuul` 和 `spring cloud gateway` 做网关: edge/zuul.md
      - nginx 网关简单介绍: edge/nginx.md
- 安全特性参考:
      - 公钥认证: references-handlers/publickey.md
      - 使用TLS通信: security/tls.md
      - 使用RSA认证: security/shi-yong-rsa-ren-zheng.md
- 服务打包和运行: 
    - 以standalone模式打包: packaging/standalone.md
    - 以WEB容器模式打包: packaging/web-container.md
- 专题文章:
    - 新功能介绍系列文章: featured-topics/features.md
    - 兼容问题和兼容性策略: featured-topics/compatibility.md
    - 升级指导系列文章: featured-topics/upgrading.md
    - 性能问题分析和调优: featured-topics/performance.md
- 常用配置项参考:
    - REST Transport Client 配置项: config-reference/rest-transport-client.md
    - Config Center Client 配置项: config-reference/config-center-client.md
    - Service Center Client 配置项: config-reference/service-center-client.md
    - ServiceComb Kie Client 配置项: config-reference/kie-client.md
- 常见问题:
    - 'FAQ' : question-and-answer/faq.md
    - 'Q & A' : question-and-answer/question_answer.md
    - 微服务接口兼容常见问题: question-and-answer/interface-compatibility.md
theme: material
plugins:
    - search
